// Generated by ts-to-zod
import { z } from 'zod'

export type GraphAttributesSchema = z.infer<typeof graphAttributesSchema>
export const graphAttributesSchema = z.object({
    category: z.string().optional(),
    label: z.string().optional(),
    author: z.string().optional(),
    authorURL: z.string().optional(),
    desc: z.string().optional(),
    tags: z.array(z.string()).optional(),
    icon: z.string().optional(),
})
export type ReplaceFileSchema = z.infer<typeof replaceFileSchema>
export const replaceFileSchema = z.object({
    pkg: z.object({
        desc: z.string(),
        metadata: z.record(z.string()).optional(),
    }),
    gph_defaults: z.object({
        attributes: graphAttributesSchema,
        metadata: z.record(z.string()).optional(),
    }),
    gph: z.record(graphAttributesSchema),
})
